# Generated by Django 3.2.7 on 2021-10-03 11:53

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('log_text', models.TextField(default='', verbose_name='Log Text')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('other_fields', models.JSONField(default=dict)),
                ('perm_save', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=api.models.File.logfiles_dir_path)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.log')),
            ],
        ),
    ]
